spring:
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    url: jdbc:h2:~/local
    driverClassName: org.h2.Driver
    username: sa
    password:
  jpa:
    properties:
      hibernate.dialect: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update


# http://localhost:8080/swagger-ui/index.html#/
springdoc:
  packages-to-scan: com.project.platform
  default-consumes-media-type: application/json;charset=UTF-8
  default-produces-media-type: application/json;charset=UTF-8
  swagger-ui:
    path: /
    disable-swagger-default-url: true
    display-request-duration: true
    operations-sorter: alpha